// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:78816083-e8bc-4cb6-875a-3f256723bb41",
    "aws_cognito_region": "ap-southeast-2",
    "aws_mobile_analytics_app_id": "e8a1d042754344109850cc5e856e5219",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "amplifyjsapp-20190107155707--hostingbucket",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "http://amplifyjsapp-20190107155707--hostingbucket.s3-website-ap-southeast-2.amazonaws.com"
};


export default awsmobile;
